# ENV CONFIG

TWITTER_CONSUMER_KEY: 'Zwnd9EFbLcTIOKQ9ABhDYiFoD'
TWITTER_CONSUMER_SECRET: 'ZOkop7eHzj2TA3d1LsebK4Xq0LLj2PXrYUOtwUd1s27PRCH9wi'
TWITTER_ACCESS_TOKEN: '1292913343221706755-QwT9z8Prkt89RRCpVgj0HyfKy6dNxH'
TWITTER_ACCESS_TOKEN_SECRET: 'LkusIvRPHECWw5q0rqMM5AvnhdFJkJ3n6lHCodHCFqL86'

TWITTER_APP_ID: 'Zwnd9EFbLcTIOKQ9ABhDYiFoD'
TWITTER_APP_SECRET: 'ZOkop7eHzj2TA3d1LsebK4Xq0LLj2PXrYUOtwUd1s27PRCH9wi'

defaults: &DEFAULTS

development:
  <<: *DEFAULTS
  APP_DOMAIN: ''
